### ISSUE TITLE
End-to-end testing capability/infra for CRI-RM.

### ISSUE THREAD

**Issue by msivosuo** [intel/cri-resource-manager#123]
- [ ] Integration/e2e validation proposal
- [ ] implement the proposal

**Comment by marquiz** [comment]
Had short brainstorming with @klihub. We agreed that the definition of end-to-end tests comprises running the (unmodified) cri-resmgr binary, against real endpoints wherever possible. One idea was to use QEMU for running end-to-end tests which would enable easy manipulation of hw topology, for example

**Comment by kad** [comment]
We need also to run official k8s compliance/node e2e subset of tests that verify that CRI behaves properly.

**Comment by mythi** [comment]
There's #185 for that. I did quickly run `cri-test` some time back but the results were not consistent (the tests were failing with vanilla containerd too).

**Comment by msivosuo** [comment]
Next steps - outline what needs to be implemented and find an owner

**Comment by askervin** [comment]
Proposing next steps:

- Study using `govm`-based E2E test stack. `govm` runs Qemu in Docker and already used by PMEM-CSI. Qemu should enable emulating what we need, while `govm` should enable doing so without messing up developer's host with dependencies and configurations.
- Validate selected E2E stack by adding `critest` tests. Critest documentation states: _CRI validation testing provides a test framework and a suite of tests to validate that the Container Runtime Interface (CRI) server implementation meets all the requirements. This allows the CRI runtime developers to verify that their runtime conforms to CRI, without needing to set up Kubernetes components or run Kubernetes end-to-end tests._

**Comment by klihub** [comment]
> Proposing next steps:
> 
> * Study using `govm`-based E2E test stack. `govm` runs Qemu in Docker and already used by PMEM-CSI. Qemu should enable emulating what we need, while `govm` should enable doing so without messing up developer's host with dependencies and configurations.

+1

**Comment by klihub** [comment]
The existing/completed govm-based exercises were good steps toward this end goal. AFAICT, what we're still lacking are:
- [ ] a way to specify the details of emulated HW for govm/tests (CPU/core to NUMA node mapping)
- [ ] a well-defined abstraction for test cases:
    - [ ] definition of emulated HW to execute test case on
    - [ ] test input artifacts: probably just a bunch of Pod YAML's
    - [ ] instructions how to execute the test: maybe an ordered set of operations on pods/YAMLs
    - [ ] expected test results: after each test step how to verify correctness of the system state

**Comment by askervin** [comment]
Working on the first step: "a way to specify the details of emulated HW for govm/tests (CPU/core to NUMA node mapping)".

**Comment by askervin** [comment]
Working on the second step: selected the standard "go test" as the runner for HW-emulating tests, too.
- Well-defined abstraction for test cases: each `TestXYZ` function defines a set of parameters for a `run.sh` scripts. The level of abstraction is these parameters. They include  NUMA node configuration for the emulated HW.
- Test input artifacts and Pod yamls: `run.sh` scripts use YAMLs and/or YAML templates for Pods and cri-resmgr configuration. In current tests these have been part of test implementation rather than input parameters, but of course we may need later on tests where similar YAMLs are part of test configuration and passed as parameters to a `run.sh`.
- Instructions to execute: using the same test runner as for all the other tests, the instructions can be very brief. However, documentation for running and developing with `run.sh` is needed, as it contains the actual test logic and in developer perspective is handy to use directly without "go test" (test case / test runner) layer.
- Expected test results: `run.sh` and its libraries are responsible for validating test steps. In the case of a failure or error, "go test" output will include last commands executed inside `run.sh` (on VM and host) together with corresponding output/timestamps. This is expected to help debugging what has gone wrong.

This approach is used in [system tests](https://github.com/askervin/cri-resource-manager/tree/57v_test_system) that run the blockio demo, the critest for CRI-RM conformance validation, and CPU pinning tests (PR #343) where emulated HW is actually built from various NUMA node configurations.

**Comment by msivosuo** [comment]
#349
