### ISSUE TITLE
Memory Tiering: Dynamic "push-out" of DRAM pages to PMEM in userspace

### ISSUE THREAD

**Issue by msivosuo** [intel/cri-resource-manager#244]
Dynamic "push-out" of DRAM pages to PMEM in userspace

Target: 2020-05-22

**Comment by ipuustin** [comment]
The algorithm would be (roughly) this:
  1. Find out which processes belong to the container.
  2. For every process in the container, find out which pages the process uses.
  3. Using `move_pages()`, push a number of pages not in the working set, which are present in DRAM, from DRAM to PMEM. This may need to be done for many times with a delay in between, because the process will be "stuck" when the pages are moved.
  4. Goto 1.

How to figure out which pages are not part of the working set:
  1. Clear soft-dirty bits on the PTEs: https://www.kernel.org/doc/html/latest/admin-guide/mm/soft-dirty.html
  2. Wait for a while.
  3. Read out the process page maps: https://www.kernel.org/doc/html/latest/admin-guide/mm/pagemap.html
  4. The pages which don't have the soft-dirty bit are considered to be outside of the working set.

Open questions:
  1. The soft-dirty mechanism helps us find the pages that are written to. How about the read-only pages?
  2. Determine the set of parameters which affect the "push-out" and find out if they should be part of the container configuration or daemon configuration. At least the following parameters can be identified: soft-dirty timer, number of pages to move in one move_pages() call, timeout between move_pages() calls.
  3. Synchronization between the page-analysis loop and the page-moving loop. Maybe there will be a "page pool" which contains the pages which should be moved in a producer-consumer fashion. It probably doesn't make sense to have addresses to all non-dirty pages in the pool at once.

**Comment by kad** [comment]
@ipuustin for open questions:
 1. Read-only pages are perfect candidates to move to PMEM. they will get almost same read performance.
  1. For such parameters we can have defaults on policy level + annotations for container level. Timer between move_pages calls is practically should be same as soft-dirty timer. We find batch, move it. If we have another non-moved candidate pages, we don't do clear refs, but just re-validate them on next cycle. And amount, in theory it should be X mb/sec, similar to autonuma kernel part. On our side the only difference should be that we don't move X mb at once, but in smaller portion and measure how fast it is done. simple TBF kind of trotting in moving.
 1. well, for large datasets, the pages considered "clean" might become dirty on next check. See previous answer.

**Comment by ipuustin** [comment]
Initial work here: https://github.com/ipuustin/cri-resource-manager/tree/dynamic-demotion

I'll make a PR when the Events PR (https://github.com/intel/cri-resource-manager/pull/286) is merged.

**Comment by eero-t** [comment]
> Read-only pages are perfect candidates to move to PMEM. they will get almost same read performance.

Because kernel can just drop unused file-backed read-only pages (e.g. library code) on memory pressure, and unwritten (just allocated) read-only pages don't take any space (AFAIK they're all physically mapped to same global zero page until written), does this concern only non-zero read-only pages that don't have file backing?

Or is there some performance data that migrating unused file-backed read-only data earlier to PMEM will help e.g. in memory usage spikes?

**Comment by klihub** [comment]
> > Read-only pages are perfect candidates to move to PMEM. they will get almost same read performance.
> 
> Because kernel can just drop unused file-backed read-only pages (e.g. library code) on memory pressure, and unwritten (just allocated) read-only pages don't take any space (AFAIK they're all physically mapped to same global zero page until written), does this concern only non-zero read-only pages that don't have file backing?
> 
> Or is there some performance data that migrating unused file-backed read-only data earlier to PMEM will help e.g. in memory usage spikes?

I think the point here was that PMEM read performance is close enough to DRAM performance, so we can unconditional migrate read-only pages, without having to worry too much about the resulting performance impact.

**Comment by msivosuo** [comment]
Implemented -> closing.
