### ISSUE TITLE
AVX512: use annotations for workload placement

### ISSUE THREAD

**Issue by mythi** [intel/cri-resource-manager#97]
Being able to utilize object metadata information (e.g., from CRI) to do proper avx512 workload placement in advance could save us from doing avx512 activity monitoring + rebalancing.

Challenges: NFD labels for instance are node affinity labels and not visible in pod metadata

**Comment by marquiz** [comment]
NFD labels Nodes, not Pods. Pods are forced/guided to run on Nodes with certain labels using `nodeSelector` or `nodeAffinity`. We don't have visibility to those.

I don't see this as a very viable or reliable method. First of all, because NFD is not part of K8s core, and second, the nodeSelector/nodeAffinity is not a reliable marker (the workload might use AVX512 even if the user didn't specify the nodeSelector, of, the workload might not use AVX512 even if the selector was present). If we really would like to do this one way would be using an admission webhook. The webhook would examine the pod spec and add pod/container annotations if certain labels are found in nodeSelector/nodeAffinity.

**Comment by mythi** [comment]
@marquiz the idea was that the pod could give us hints it's using avx512 and CRI-RM would take those. This issue just tracks the idea. We already discussed that NFD labels are not usable here as is.

**Comment by marquiz** [comment]
@mythi @klihub let's close this one, too?

**Comment by mythi** [comment]
closing since not relevant anymore
